easy_admin:
  entities:
    Category:
      class: AppBundle\Entity\Category
    Stock:
      class: AppBundle\Entity\Stock
      list:
        fields:
          - "id"
          - "filename"
          - "slug"
          - { property: "width", format: "%d" }
          - { property: "height", format: "%d" }
          - { property: "image", type: "image", base_path: "/images/"}